import { describe, expect, test } from 'bun:test'
import { isAmagiCommit, lintCommitMessage } from './commit-lint.ts'

const GOOD =
  '[am-1] Add a greeting file\n\nReaders were never greeted.\n\nGenerated by amagi · claude\n'

describe('lintCommitMessage', () => {
  test('accepts a well-formed amagi commit', () => {
    expect(lintCommitMessage(GOOD)).toEqual([])
  })

  test('leaves commits amagi did not make alone', () => {
    const human = 'core: fix it\n\nChanges:\n- `a.ts` +1 -0\n'
    expect(isAmagiCommit(human)).toBe(false)
    expect(lintCommitMessage(human)).toEqual([])
  })

  test('rejects the per-file changes list', () => {
    const message = GOOD.replace('greeted.\n', 'greeted.\n\nChanges:\n- `hello.txt` +1 -0\n')
    expect(lintCommitMessage(message)).toEqual([
      'body must not list the changed files; the diff shows them',
    ])
  })

  test('rejects a [task-id] commit without the footer or a summary', () => {
    expect(lintCommitMessage('[am-1] Add a greeting file\n')).toEqual([
      'last line must be the `Generated by amagi` footer',
      'body must summarize the change',
    ])
  })

  test('rejects a footer commit whose subject lost the task id', () => {
    const message = GOOD.replace('[am-1] ', '')
    expect(lintCommitMessage(message)).toEqual(['subject must start with `[task-id] `'])
  })

  test('rejects a body glued to the subject', () => {
    expect(lintCommitMessage(GOOD.replace('file\n\n', 'file\n'))).toEqual([
      'subject must be followed by a blank line',
    ])
  })
})
