function provenance(harness: string, model: string | null, effort: string | null): string[] {
  const bits = [harness]
  if (model !== null && model !== '') bits.push(model)
  if (effort !== null && effort !== '') bits.push(`effort ${effort}`)
  return bits
}

/**
 * One-line provenance footer for model-generated content (PR bodies and model
 * replies): a markdown horizontal rule plus a small-print line naming the
 * harness, model, and effort that produced it. Empty when nothing beyond the
 * harness is known, so callers skip it silently.
 */
export function modelFooter(harness: string, model: string | null, effort: string | null): string {
  const bits = provenance(harness, model, effort)
  if (bits.length === 1) return ''
  return `\n\n---\n\n<sub>Generated by amagi · ${bits.join(' · ')}</sub>`
}

/** Marks an amagi commit; commit-lint.ts keys on it. */
export const COMMIT_FOOTER_PREFIX = 'Generated by amagi'

/**
 * The PR body footer as plain text, the last line of every amagi commit. Always
 * present, unlike modelFooter, because it is what identifies the commit.
 */
export function commitFooter(harness: string, model: string | null, effort: string | null): string {
  return [COMMIT_FOOTER_PREFIX, ...provenance(harness, model, effort)].join(' · ')
}
