import { describe, expect, test } from 'bun:test'
import { lintCommitMessage } from './commit-lint.ts'
import type { TrackerTask } from './drivers/types.ts'
import {
  classifyMentionPrompt,
  commitMessage,
  commitSummary,
  implementPrompt,
  implementSystemPrompt,
  prFailurePrompt,
  prFailureSystemPrompt,
  prTitle,
} from './prompt.ts'

const TASK: TrackerTask = {
  id: 'am-1',
  title: 'Add a greeting file',
  description: 'Write hello.txt',
  status: 'in_progress',
  priority: 1,
  type: 'task',
  url: null,
}

describe('commitMessage', () => {
  const META = { harness: 'claude', model: 'opus', effort: 'high' }

  test('renders the [task-id] subject, the summary and the amagi footer', () => {
    const message = commitMessage(TASK, 'Greets the reader.\n', META)
    expect(message).toBe(
      '[am-1] Add a greeting file\n\nGreets the reader.\n\nGenerated by amagi · claude · opus · effort high\n',
    )
    expect(lintCommitMessage(message)).toEqual([])
  })

  test('keeps the footer when only the harness is known', () => {
    const message = commitMessage(TASK, 'Greets the reader.', {
      ...META,
      model: null,
      effort: null,
    })
    expect(message.trim().split('\n').at(-1)).toBe('Generated by amagi · claude')
  })
})

describe('commitSummary', () => {
  test('keeps the opening summary, dropping the sections and the verdict line', () => {
    const final =
      'Readers were never greeted.\nAdds `hello.txt`.\n\nVerdict: close-task\n\n### Conclusion\n\n- hello.txt: new'
    expect(commitSummary(final)).toBe('Readers were never greeted.\nAdds `hello.txt`.')
  })

  test('falls back to a placeholder when the agent reported nothing', () => {
    expect(commitSummary(null)).not.toBe('')
    expect(commitSummary('### Conclusion\n\nx')).not.toBe('')
  })
})

const task = (title: string): TrackerTask => ({
  id: 'am-544',
  title,
  description: '',
  status: 'in_progress',
  priority: null,
  type: 'task',
  url: null,
})

describe('prFailurePrompt', () => {
  test('asks the agent to recover from PR creation or give the manual next step', () => {
    const prompt = prFailurePrompt(TASK, 'amagi/am-1-change', 'gh not authenticated')
    expect(prompt).toContain('gh not authenticated')
    expect(prompt).toContain('Resolve the problem if you can')
    expect(prompt).toContain('retry pull request creation once')
    expect(prompt).toContain('exact manual\nnext step')
    expect(prompt).toContain('Do not change project files, git history, branches, or remotes')
  })

  test('allows safe recovery actions without opening the PR directly', () => {
    const prompt = prFailureSystemPrompt()
    expect(prompt).toContain('safely correct its cause')
    expect(prompt).toContain('the runner will retry once')
    expect(prompt).toContain('Do not commit or push')
  })
})

describe('prTitle', () => {
  test('prepends the task code to a short title', () => {
    expect(prTitle(task('Forgejo driver over tea'))).toBe('am-544: Forgejo driver over tea')
  })

  test('cuts a full sentence at the first clause', () => {
    expect(prTitle(task('PR titles should use task code, not full sentences'))).toBe(
      'am-544: PR titles should use task code',
    )
  })

  test('drops a milestone-style prefix', () => {
    expect(prTitle(task('M5: forge drivers'))).toBe('am-544: forge drivers')
  })
})

describe('implementSystemPrompt', () => {
  test('tells the agent to document how to use new user-facing features', () => {
    const prompt = implementSystemPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).toContain('user-facing feature')
    expect(prompt).toContain('### How to use')
    expect(prompt).toContain('final message')
  })

  test('tells the agent not to pipe check or lint output through head/tail', () => {
    const prompt = implementSystemPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).toContain('Never pipe check or lint output through head/tail')
    expect(prompt).toContain('Redirect to a file instead')
  })

  test('keeps the agent off bd: the issue text is embedded and sections are written back', () => {
    const prompt = implementSystemPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).toContain('Never edit issues with the tracker CLI (bd)')
    expect(prompt).toContain('embedded in the')
    expect(prompt).toContain('writes the sections')
  })

  test('names the gate commands so the agent need not discover them', () => {
    const prompt = implementSystemPrompt({
      task: task('Add a flag'),
      worktree: '/wt',
      branch: 'b',
      checks: ['just fmt', 'just lint', 'just check'],
    })
    expect(prompt).toContain('`just fmt`, `just lint`, `just check`')
    expect(prompt).not.toContain('e.g. `just fmt`')
  })

  test('a clean tree is not a valid outcome for investigation-style tasks', () => {
    const prompt = implementSystemPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).toContain('investigation-style tasks')
    expect(prompt).toContain('clean working tree is not a valid outcome')
  })

  test('asks for a mandatory conclusion in the final message, written against the real diff', () => {
    const prompt = implementSystemPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).toContain('### Conclusion')
    expect(prompt).toContain('Verdict: <label>')
    expect(prompt).toContain('`close-task`')
    expect(prompt).toContain('git diff --stat <base>')
    expect(prompt).toContain('file by file')
    expect(prompt).toContain('Whenever the summary or Conclusion refers to more than one file')
    expect(prompt).toContain('bullet list with one file per line')
    expect(prompt).toContain('Never join multiple file paths with commas in a sentence')
    expect(prompt).toContain('mandatory')
    expect(prompt).toContain('deviations from')
  })
})

describe('implementPrompt', () => {
  test('embeds notes and comments so the agent sees them without bd', () => {
    const ctx = {
      task: {
        ...task('Investigate the crash'),
        notes: 'root cause: biome EPIPE panic when piped through head/tail',
        comments: ['try the fix', '  '],
      },
      worktree: '/wt',
      branch: 'b',
    }
    const prompt = implementPrompt(ctx)
    expect(prompt).toContain('Issue notes:')
    expect(prompt).toContain('root cause: biome EPIPE panic when piped through head/tail')
    expect(prompt).toContain('Issue comments:')
    expect(prompt).toContain('- try the fix')
    expect(prompt).not.toContain('-   ')
  })

  test('omits notes and comments sections when the tracker has none', () => {
    const prompt = implementPrompt({ task: task('Add a flag'), worktree: '/wt', branch: 'b' })
    expect(prompt).not.toContain('Issue notes:')
    expect(prompt).not.toContain('Issue comments:')
  })
})

describe('classifyMentionPrompt', () => {
  test('maps questions about a change still being relevant to explain, not ambiguous', () => {
    const prompt = classifyMentionPrompt({
      pr: { number: 102, title: 'Revert PR #36', url: 'https://github.com/owner/repo/pull/102' },
      mention: { user: 'mcpie87', body: '@chise-maru is this change still relevant?' },
    })
    expect(prompt).toContain('explain: the human is asking anything about the PR')
    expect(prompt).toContain('still relevant')
    expect(prompt).toContain('never ambiguous')
  })
})
